# Generated by Django 5.1.3 on 2024-12-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='untuk kamu', max_length=100)),
                ('content', models.TextField(default='untuk kamu')),
                ('video_url', models.URLField(default='https://www.youtube.com/watch?v=VGq0wZBbOG0')),
                ('image', models.ImageField(default='assets/img/about.jpg', upload_to='assets/img/')),
            ],
        ),
    ]
