# Generated by Django 5.1.5 on 2025-01-20 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_alter_aboutsection_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='assets/img/company/logo.png', upload_to='assets/img/company/')),
                ('deskripsi', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=100)),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('alamat', models.TextField()),
                ('pelanggan', models.IntegerField()),
                ('projek', models.IntegerField()),
                ('pekerja', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('periode', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berita.company')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berita.company')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('pesan', models.TextField()),
                ('star', models.SmallIntegerField()),
                ('image', models.ImageField(default='assets/img/testimonials/testimonials-1.jpg', upload_to='assets/img/testimonials/')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berita.company')),
            ],
        ),
    ]
