# Generated by Django 5.1.5 on 2025-01-21 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0005_company_pricing_service_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='featured',
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='assets/img/gallery/gallery-1.jpg', upload_to='assets/img/gallery/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berita.company')),
            ],
        ),
        migrations.CreateModel(
            name='PricingFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField()),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berita.company')),
            ],
        ),
        migrations.AddField(
            model_name='pricing',
            name='features',
            field=models.ManyToManyField(blank=True, to='berita.pricingfeatures'),
        ),
    ]
