# Generated by Django 5.1.5 on 2025-01-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0006_remove_pricing_featured_gallery_pricingfeatures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='banner',
            field=models.ImageField(default='assets/img/company/logo.png', upload_to='assets/img/company/'),
        ),
    ]
